"""Remove renting columns from Transaction

Revision ID: b1b261343327
Revises: 3126254c76f9
Create Date: 2025-05-05 23:08:19.530661

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b1b261343327'
down_revision = '3126254c76f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('rent_start_date')
        batch_op.drop_column('rent_end_date')
        batch_op.drop_column('return_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('return_date', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('rent_end_date', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('rent_start_date', mysql.DATETIME(), nullable=True))

    # ### end Alembic commands ###
